Add If and Else Tutorials
bowbahdoe/ModernJava pull request #12
Opened 2023-01-12 15:53 UTC by coderFlameyosFlow

- [x] The code has been tested when writing the tutorials
- [ ] This includes all `if and else` tutorials

This excludes `9.1.1. relations and delayed assignments`.

2023-01-12 18:07 UTC, illuminator3 commented on src/if_else/floating_point_comparisons.md
> +If you don't know the conditions in java, we'd suggest you to check out [this](./if_else/if_statement.md)
"the conditions in java"?

2023-01-12 18:07 UTC, illuminator3 commented on src/if_else/if_and_else.md
> +- `else if` - mix of "if" and "else", runs some other code if an "if" statement returns false.
"runs some other code"?

2023-01-12 18:07 UTC, illuminator3 commented on src/if_else/if_and_else.md
> +- `else if` - mix of "if" and "else", runs some other code if an "if" statement returns false.
"if an 'if' statement returns false", what if statement?

2023-01-12 18:08 UTC, illuminator3 commented on src/if_else/if_and_else.md
> +- `if` - the classic "if" statement.
"the classic"?

2023-01-12 18:08 UTC, illuminator3 commented on src/if_else/if_and_else.md
> +- `else` - "else" statement to check if the same condition is false.
"the same condition"?

2023-01-12 18:08 UTC, illuminator3 commented on src/if_else/if_statement.md
> +If statements are useful in many cases you want to check something.
this has a grammar mistake

2023-01-12 18:08 UTC, illuminator3 commented on src/if_else/if_statement.md
> +Available logical conditions:
I'd say expressions not conditions

2023-01-12 18:09 UTC, illuminator3 commented on src/if_else/if_statement.md
> +For example, We're using `>`:
grammatical error

2023-01-12 18:09 UTC, illuminator3 commented on src/if_else/integer_comparisons.md
> +If you don't know the conditions in java, we'd suggest you to check out [this](./if_else/if_statement.md)
"the conditions in java"?

2023-01-12 18:09 UTC, illuminator3 commented on src/if_else/integer_comparisons.md
> +If you don't know the conditions in java, we'd suggest you to check out [this](./if_else/if_statement.md)
"this"?

2023-01-12 18:09 UTC, illuminator3 commented on src/if_else/floating_point_comparisons.md
> +If you don't know the conditions in java, we'd suggest you to check out [this](./if_else/if_statement.md)
"this"?

2023-01-12 18:09 UTC, illuminator3 commented on src/if_else/string_comparisons.md
> +Normally to check if something is equal to something, this code would be used:
grammar mistake

2023-01-12 18:10 UTC, illuminator3 commented on src/if_else/string_comparisons.md
> +Why? because for **primitive types** (such as `int`, `float`, etc), `==` compares **values**, although **for Objects** (such as `String` and `User-Defined Classes`) and Arrays, `==` compares **refere
"etc"?

2023-01-12 18:10 UTC, illuminator3 commented on src/if_else/string_comparisons.md
> +Why? because for **primitive types** (such as `int`, `float`, etc), `==` compares **values**, although **for Objects** (such as `String` and `User-Defined Classes`) and Arrays, `==` compares **refere
'String and User-Defined Classes' aren't objects

2023-01-12 18:11 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +It's a way of doing an `if` and `else` in one line as an expression, the **rules of this are simple**:
grammar mistake

2023-01-12 18:11 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +It's a way of doing an `if` and `else` in one line as an expression, the **rules of this are simple**:
"of this"?

2023-01-12 18:11 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +This is typically used with methods OR to replace a simple if...else statement with one line each condition.
grammar mistake

2023-01-12 18:11 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +example:
should be capitalized

2023-01-12 18:11 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +if (4 > 2) { // boolean expression which is true
grammar mistake

2023-01-12 18:12 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +    whatsGreater = "4 > 2"; // one line condition of "if"
"one line condition of 'if'"?

2023-01-12 18:12 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +    whatsGreater = "2 > 4"; // another one line condition of "else"
"another one line condition of 'else'"?

2023-01-12 18:12 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +} else { // cannot run
why can't it "run"?

2023-01-12 18:12 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +can be fully replaced with:
should be capitalized

2023-01-12 18:12 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +Which is really nice of java to have. ~~*gotta delete all them lines*~~
"~~*gotta delete all them lines*~~"?

2023-01-12 18:12 UTC, illuminator3 commented on src/if_else/ternary_expressions.md
> +Which is really nice of java to have. ~~*gotta delete all them lines*~~
it's Java not java

2023-01-12 18:15 UTC, illuminator3 commented on src/if_else/if_and_else.md
> +} else { // This runs if everything else is false.
"everything else"?

2023-01-12 18:46 UTC, Taz03 requested changes

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +These are statements that check if something is `true` or `false`.
they do more than that, they also execute some code

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/floating_point_comparisons.md
> +} else { // not running because it's impossible for 56.78 to be greater than 56.79
"not running"?

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +```
take a more relatable example with shorter variable name

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +} else if (badVibesAreGood) { // this runs if "youtubeIsAmazing" is false.
fix the comment

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +```
same thing there

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +You can have multiple `if` and `else if` statements, but not multiple `else` statements
instead write "but only one `else`..."

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +You can have multiple `if` and `else if` statements, but not multiple `else` statements
what do u mean u can have multiple `if` statement but not multiple `else`?

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/integer_comparisons.md
> +} else { // not running because it's impossible for 60 to be greater than 400
"not running"?, also y say impossible, write the reason instead

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/string_comparisons.md
> +but for strings, it's an entirely different story, as we use `.equals` (inherited from `Object`) instead of `==`
make the first letter capital

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/ternary_expressions.md
> +This is typically used with methods OR to replace a simple if...else statement with one line each condition.
"with one line each condition"?

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/ternary_expressions.md
> +String whatsGreater;
not conventionally correct naming

2023-01-12 18:46 UTC, Taz03 commented on src/if_else/ternary_expressions.md
> +String whatsGreater = 4 > 2 ? "4 > 2" : "2 > 4";
same thing here

2023-01-13 13:31 UTC, bowbahdoe requested changes

2023-01-13 13:31 UTC, bowbahdoe commented on src/if_else/if_statement.md
> +- `a >= b` - greater than or equal to
Already covered with numbers

2023-01-13 13:31 UTC, bowbahdoe commented on src/if_else/string_comparisons.md
> +Why? because for **primitive types** (such as `int`, `float`, etc), `==` compares **values**, although **for Objects** (such as `String` and `User-Defined Classes`) and Arrays, `==` compares **refere
This terminology is relatively quickly going to be inaccurate. `primitive` and `reference` types will be objects and the two kinds of `reference` types - `value` types and `identity` types will compare based on their "value" or their "identity"

2023-01-13 13:31 UTC, bowbahdoe commented on src/if_else/string_comparisons.md
> +Why? because for **primitive types** (such as `int`, `float`, etc), `==` compares **values**, although **for Objects** (such as `String` and `User-Defined Classes`) and Arrays, `==` compares **refere
Bit too much bold here.

2023-01-13 13:31 UTC, bowbahdoe commented on src/if_else/string_comparisons.md
> +Why? because for **primitive types** (such as `int`, `float`, etc), `==` compares **values**, although **for Objects** (such as `String` and `User-Defined Classes`) and Arrays, `==` compares **refere
Arrays haven't been introduced yet

2023-01-13 13:31 UTC, bowbahdoe commented on src/if_else/ternary_expressions.md
> +It's a way of doing an `if` and `else` in one line as an expression, the **rules of this are simple**:
Why bold? `**rules of this are simple**`

2023-01-13 13:31 UTC, bowbahdoe commented on src/if_else/ternary_expressions.md
> +Which is really nice of java to have. ~~*gotta delete all them lines*~~
Is this a pokemon reference? I have all the pokemon in a living dex up til gen 7, If i have to ask its too vague

2023-01-13 13:46 UTC, Taz03 requested changes

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/floating_point_comparisons.md
> +double anotherNumber = 56.79; // notice the .01 difference
notice the difference of .01, sounds better

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/floating_point_comparisons.md
> +Here's an example of a floating point number comparison between a number and another.
comparison between 2 numbers

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +# `if and else` statements
i'd go for if-else statements

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/if_and_else.md
> +# `if and else` statements
also i don't think putting title in code block is a good idea

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/if_statement.md
> +boolean numberGreaterThanNumber = 20 > 15; // boolean expression
not good name

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/string_comparisons.md
> +if (one == anotherOne) {
add a comment // true for consistency

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/string_comparisons.md
> +Why? because for **primitive types** (such as `int`, `float`, etc), `==` compares **values**, although **for Objects** (such as `String` and `User-Defined Classes`) and Arrays, `==` compares **refere
objects and references are later topics so just add a little comment in braces defining references

2023-01-13 13:46 UTC, Taz03 commented on src/if_else/floating_point_comparisons.md
> +# `Floating Point Number` comparisons.
we should discuss using code blocks in title

2023-02-13 08:36 UTC, closed without merging