Add a couple of challenges for string section
bowbahdoe/ModernJava pull request #15
Opened 2023-02-25 02:41 UTC by ankitsmt211

adds three challenges for `String` section

2023-02-25 05:21 UTC, Taz03 requested changes
fix formatting

2023-02-25 05:41 UTC, ankitsmt211 commented
@Taz03 how do i do that?

2023-02-25 05:47 UTC, Taz03 commented
if ur good enough then u should know how properly formatted java code looks likes, otherwise use ur ide and also get  better

2023-02-25 05:53 UTC, ankitsmt211 commented
@Taz03 i don't appreciate such comments, there's no need for it. There's no guidelines whatsoever anywhere in project, so i did my best.

2023-02-25 05:56 UTC, Taz03 commented
y u don't like it, i just said how to format ur code, i can even do it for u

2023-02-25 06:02 UTC, ankitsmt211 commented
>if you are good enough then you should know how to format your code

this
>get better

and this

there's no need for these comments, you could have simply either pointed me to a direction or what convention to follow or just ignored it and let someone else help.

2023-02-25 11:34 UTC, Taz03 requested changes

2023-02-25 11:34 UTC, Taz03 commented on src/strings/challenges.md
> +
remove this empty line

2023-02-25 11:34 UTC, Taz03 commented on src/strings/challenges.md
> +
.

2023-02-25 11:34 UTC, Taz03 commented on src/strings/challenges.md
> +
.

2023-02-25 11:34 UTC, Taz03 commented on src/strings/challenges.md
> +## challenge 1
first letter should be capital, no?

2023-02-25 11:34 UTC, Taz03 commented on src/strings/challenges.md
> +## challenge 2
.

2023-02-25 11:34 UTC, Taz03 commented on src/strings/challenges.md
> +## challenge 3
.

2023-02-25 22:35 UTC, marko-radosavljevic commented
@Taz03 Please be friendlier, you know we don't tolerate such attitudes. :)

Apologies for that @ankitsmt211, and thank you for your contribution. :relaxed: :heart:

2023-02-25 22:42 UTC, marko-radosavljevic commented
At some point we should align on the formatting, but it's not terribly important at this stage.
 
Default intellij / google style is fine, which is basically the formatting we have been using for tj-bot too.

2023-02-26 02:36 UTC, Taz03 commented
@ankitsmt211 sorry ankit, don't get better

2023-03-15 02:28 UTC, bowbahdoe commented
@ankitsmt211 I am going to integrate these on another branch.

2023-03-15 03:16 UTC, bowbahdoe commented
@ankitsmt211 Integrated. Added you as co-author for that PR

2023-03-15 03:16 UTC, closed without merging